import mammoth from 'mammoth';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';
import FileSaver from 'file-saver';
import { QuestionItem } from '../types';

/**
 * Extracts raw text from a DOCX file using Mammoth.
 */
export const extractTextFromDocx = async (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const arrayBuffer = e.target?.result as ArrayBuffer;
        if (!arrayBuffer) {
          reject(new Error("Empty file"));
          return;
        }
        const result = await mammoth.extractRawText({ arrayBuffer });
        resolve(result.value);
      } catch (error) {
        reject(error);
      }
    };
    reader.onerror = (error) => reject(error);
    reader.readAsArrayBuffer(file);
  });
};

/**
 * Extracts text from plain text files.
 */
export const extractTextFromTxt = async (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => resolve(e.target?.result as string);
    reader.onerror = (error) => reject(error);
    reader.readAsText(file);
  });
};

/**
 * Generates a new DOCX file containing the Q&A pairs.
 */
export const generateFilledDocx = async (qaPairs: QuestionItem[]) => {
  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: "Solved Question Bank",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  );

  children.push(
    new Paragraph({
      text: `Generated by AutoSolver AI on ${new Date().toLocaleDateString()}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
      border: {
        bottom: { color: "auto", space: 1, style: BorderStyle.SINGLE, size: 6 },
      },
    })
  );

  // Content
  for (const item of qaPairs) {
    // The Question
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: "Q: ",
            bold: true,
            color: "2E75B6", // Blue
            size: 24,
          }),
          new TextRun({
            text: item.originalText,
            bold: true,
            size: 24,
          }),
        ],
        spacing: { before: 400, after: 200 },
      })
    );

    // The Answer
    const answerText = item.answer || "No answer generated.";
    
    // Split answer by newlines to create proper paragraphs
    const answerLines = answerText.split('\n');
    
    answerLines.forEach((line) => {
        if(line.trim() !== '') {
            children.push(
                new Paragraph({
                  children: [
                    new TextRun({
                        text: line,
                        size: 22,
                      }),
                  ],
                  spacing: { after: 120 },
                })
              );
        }
    });

    // Separator
    children.push(
        new Paragraph({
            text: "______________________________________________________",
            alignment: AlignmentType.CENTER,
            spacing: { before: 200, after: 200 },
            style: "Disabled", 
        })
    );
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  FileSaver.saveAs(blob, "Solved_Question_Bank.docx");
};